### ISSUE TITLE
Pip install does not work

### ISSUE THREAD

**Issue by Yukun-Xie** [KWR-Water/pysimdeum#17]
(1) As title, 'pip install pysimdeum' does not work, while 'pip install git+https://github.com/KWR-Water/pysimdeum.git'works.
(2) In the instruction, 'house = pySIMDEUM.built_house(house_type='one_person')' will not work because the package's name is 'pysimdeum', without upper letter
(3) Duration and num_pattern keyword seems useless. In the instruction, It is suggested to write keyword 'num_pattern = 100', but the truth is that same program will run for 100 times and all data will be stored in one day(86400s). The same situation will happen when you type in, for example, duration = '5 days' , although 5 days time span will be create, all data will be write in the first day and keep overwriting.

**Comment by BramHillebrand** [comment]
1) for me pip install does work
2) it should indeed be lower case. Where does it still say pySIMDEUM?
3) if you use num_patterns=100 it will create 100 separate 1 day patterns. Which are also split into user and appliance so the xarray dataarray has 4 dimensions 1 time, 2 users, 3 appliances and 4 patterns.

do take care that the keyword is `num_patterns` and not num_pattern

**Comment by Yukun-Xie** [comment]
(1) If the pip install does not work, pls try following code:
pip install pysimdeum -i http://pypi.douban.com/simple/ --trusted-host pypi.douban.com
