### ISSUE TITLE
Change the properties of household

### ISSUE THREAD

**Issue by Wang-Shu-Wei** [KWR-Water/pysimdeum#20]
How can I change the properties of the household by editing the input?

E.g., if I want to get the consumption profile for a two_person household but both of them are senior. How can I realize this?

Thanks in advance.

**Comment by Yukun-Xie** [comment]
I don't think two senior is a possible senario. Possible senarios for two person include father + senior, mother + senior and an adult couple. You can choose one person, two person or familty while I think changing exact properties is not possible up to now. Maybe in a later version.

**Comment by BramHillebrand** [comment]
You can achieve this by manipulating the statistics object and enforcing 2 seniors (make the chances for a 2 person senior household 100% and the others 0). We are working on an example to show how to manipulate the statistics object.

For now you can either load the statistics object (see statistics.py and api.py how to work with statistics) and manipulate the statistics.household object or you can make a copy of the stats folder (data/NL/) manipulate the household_statistics.toml

 directly and create a statistics object with `stats = Statistics(statisticsdir='myfolder')`
