### ISSUE TITLE
Simulating multiple days

### ISSUE THREAD

**Issue by mariekeberlin** [KWR-Water/pysimdeum#21]
The following code only gives a simulated water consumption of the first day. However, the water consumption of the second day is zero. 
house=pysimdeum.built_house()
consumption=house.simulate(duration='2 day', num_patterns=100).sum(['enduse', 'user'])

**Comment by BramHillebrand** [comment]
If a dishwasher or washing machine is simulated on another day than the first the simulation still fails. This is being adressed now.
