### ISSUE TITLE
Possible typo in user (core)

### ISSUE THREAD

**Issue by mariekeberlin** [KWR-Water/pysimdeum#22]
In line 101 night is set to be equal to 0.015, however in line 178 night is set equal to 0.15. I think this could be a typo since Stochastic water demand modelling for a better understanding of hydraulics in water distribution networks written by Mirjam Blokker assumes that approximately 1.5% of the water is used during the night.

**Comment by BramHillebrand** [comment]
This is indeed a typo. Will be fixed in an upcoming version
