### ISSUE TITLE
Selecting specific day/week

### ISSUE THREAD

**Issue by risidlo** [KWR-Water/pysimdeum#37]
Hello everybody,

is somehow possible to simulate demand for specific time of the year? I want to simulate e.g. summer week/winter week etc. and I dont know how to select specific time. I always get actual date. Thx

**Comment by BramHillebrand** [comment]
To elaborate on this: Seasonality can always be added by changing the statistics (the TOML files). Here you can adjust the frequency of use (of for instance the outside tap) to more resemble a hot summer day (for instance). 

pysimdeum was based on a matlab code called SIMDEUM (1) with which some studies into seasonality have been performed.
Some of those features might be added to pysimdeum in a later stage.

For now it is best to directly contact either me (bram.hillebrand@kwrwater.nl) or Mirjam Blokker (mirjam.blokker@kwrwater.nl)

(1) Blokker, M., Agudelo-Vera, C., Moerman, A., van Thienen, P., and Pieterse-Quirijns, I.: Review of applications for SIMDEUM, a stochastic drinking water demand model with a small temporal and spatial scale, Drink. Water Eng. Sci., 10, 1–12, https://doi.org/10.5194/dwes-10-1-2017, 2017.
